### ISSUE TITLE
Can't get iteration number in Backend listener

### ISSUE THREAD

**Issue by sivaram-vu** [delirius325/jmeter-elasticsearch-backend-listener#27]
Any idea how we can get the iteration number in backend listener?

**Comment by delirius325** [comment]
Hey there,

First of all thanks for reporting the issue. I will look into it as soon as I can. Might be able to access it through JMeter's context service, otherwise I might have to try and figure out a way of calculating it myself.

Cheers,

**Comment by delirius325** [comment]
Hi @sivaram-vu,

So I'm looking into the issue right now. It's definitely feasible, but what you could simply do is adding a custom field to your listener! :) (new feature added in [version 2.3.2](https://github.com/delirius325/jmeter-elasticsearch-backend-listener/releases/tag/2.3.2)). Here's how you could do it.

1. Add a field in the backend listener
2. Name it what you want (i.e : threadIteration)
3. Assign the following value : ```${__groovy(return vars.getIteration();)}```

<img width="946" alt="screen shot 2018-07-16 at 8 26 47 am" src="https://user-images.githubusercontent.com/6709533/42758756-89dbc922-88d2-11e8-98bf-0be0687a7584.png">

Thanks,

**Comment by delirius325** [comment]
Hello @pmouawad ,

I'm requiring your assistance regarding this issue. I am unable to access the JMeter variables through the JMeterContextService. 

The way I understand it is that the Backend Listener is set before the test plan is started, therefore before the threads are started. Because of that, when calling the method ```JMeterContextService.getContext();``` I'm unable to retrieve the context since it's related to a thread in particular.

It all makes sense really, but would you happen to know if there is a way to access the variables inside a backend listener (programmatically that is, not like the method listed above) ?

Thanks,

**Comment by pmouawad** [comment]
Hello,
You can't access JMeter variables or JMeterContextService.getContext() from a BackendListenerClient as the threads of VU are different from Listener thread.

What is the use case behind this particular issue ?

**Comment by delirius325** [comment]
@pmouawad Thank you for responding. That's what I thought and it totally makes sense. As for the use case, we'd have to ask @sivaram-vu. 

Anyways, since this is impossible to achieve from within the plugin's code, the only way to achieve this behaviour would be through the solution I described above. If it doesn't work, then I'm afraid it's impossible to achieve what you want @sivaram-vu.

Thanks everyone, I'll be closing this issue since there's nothing more we can do. Although feel free to keep the conversation going.

**Comment by sivaram-vu** [comment]
Thank you for responding.

I just wanted to check if I can pass user variables to DB for the reporting purposes.
For example, Order created in the iteration need to be logged in to DB.

I feel fields in backend listener also can not access user variables as they simply do not exist in the context of backend listener.

**Comment by delirius325** [comment]
Hi @sivaram-vu ,

I've been able to access variables from the Test Plan & from a CSV (loaded before thread groups). But indeed unable to access variables that are scoped within thread groups (whether they're dynamic or not). It it in fact due to the way JMeter works and there is nothing I can do on my end to allow this 😢 .

A work around could be for you to put the listener's test mode in "debug" and have a JSR223 sampler (or a Dummy Sampler) logging the details in the request body. It's not pretty but it works.

Thanks,
